version: '3.8'

services:
  hass-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/timstoop/upstream/hass-mcp:latest
    environment:
      - HA_URL=${HA_URL}
      - HA_TOKEN=${HA_TOKEN}
    volumes:
      # Mount app directory for development (optional - comment out for production)
      - ./app:/app/app:ro
    stdin_open: true
    tty: true
    restart: unless-stopped

  # Development service with hot reload
  hass-mcp-dev:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - HA_URL=${HA_URL}
      - HA_TOKEN=${HA_TOKEN}
    volumes:
      # Mount for development with write access
      - ./app:/app/app
      - ./tests:/app/tests
    stdin_open: true
    tty: true
    command: python -m app
    profiles:
      - dev